# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kn1ght/CLionProjects/notebar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kn1ght/CLionProjects/notebar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kn1ght/CLionProjects/notebar/CMakeFiles /home/kn1ght/CLionProjects/notebar//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kn1ght/CLionProjects/notebar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named notebar

# Build rule for target.
notebar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 notebar
.PHONY : notebar

# fast build rule for target.
notebar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/build
.PHONY : notebar/fast

ProcessManager.o: ProcessManager.cpp.o

.PHONY : ProcessManager.o

# target to build an object file
ProcessManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/ProcessManager.cpp.o
.PHONY : ProcessManager.cpp.o

ProcessManager.i: ProcessManager.cpp.i

.PHONY : ProcessManager.i

# target to preprocess a source file
ProcessManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/ProcessManager.cpp.i
.PHONY : ProcessManager.cpp.i

ProcessManager.s: ProcessManager.cpp.s

.PHONY : ProcessManager.s

# target to generate assembly for a file
ProcessManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/ProcessManager.cpp.s
.PHONY : ProcessManager.cpp.s

bar/Bar.o: bar/Bar.cpp.o

.PHONY : bar/Bar.o

# target to build an object file
bar/Bar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/bar/Bar.cpp.o
.PHONY : bar/Bar.cpp.o

bar/Bar.i: bar/Bar.cpp.i

.PHONY : bar/Bar.i

# target to preprocess a source file
bar/Bar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/bar/Bar.cpp.i
.PHONY : bar/Bar.cpp.i

bar/Bar.s: bar/Bar.cpp.s

.PHONY : bar/Bar.s

# target to generate assembly for a file
bar/Bar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/bar/Bar.cpp.s
.PHONY : bar/Bar.cpp.s

bar/Note.o: bar/Note.cpp.o

.PHONY : bar/Note.o

# target to build an object file
bar/Note.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/bar/Note.cpp.o
.PHONY : bar/Note.cpp.o

bar/Note.i: bar/Note.cpp.i

.PHONY : bar/Note.i

# target to preprocess a source file
bar/Note.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/bar/Note.cpp.i
.PHONY : bar/Note.cpp.i

bar/Note.s: bar/Note.cpp.s

.PHONY : bar/Note.s

# target to generate assembly for a file
bar/Note.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/bar/Note.cpp.s
.PHONY : bar/Note.cpp.s

bar/Size.o: bar/Size.cpp.o

.PHONY : bar/Size.o

# target to build an object file
bar/Size.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/bar/Size.cpp.o
.PHONY : bar/Size.cpp.o

bar/Size.i: bar/Size.cpp.i

.PHONY : bar/Size.i

# target to preprocess a source file
bar/Size.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/bar/Size.cpp.i
.PHONY : bar/Size.cpp.i

bar/Size.s: bar/Size.cpp.s

.PHONY : bar/Size.s

# target to generate assembly for a file
bar/Size.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/bar/Size.cpp.s
.PHONY : bar/Size.cpp.s

config.o: config.cpp.o

.PHONY : config.o

# target to build an object file
config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/config.cpp.o
.PHONY : config.cpp.o

config.i: config.cpp.i

.PHONY : config.i

# target to preprocess a source file
config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/config.cpp.i
.PHONY : config.cpp.i

config.s: config.cpp.s

.PHONY : config.s

# target to generate assembly for a file
config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/config.cpp.s
.PHONY : config.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/notebar.dir/build.make CMakeFiles/notebar.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... notebar"
	@echo "... ProcessManager.o"
	@echo "... ProcessManager.i"
	@echo "... ProcessManager.s"
	@echo "... bar/Bar.o"
	@echo "... bar/Bar.i"
	@echo "... bar/Bar.s"
	@echo "... bar/Note.o"
	@echo "... bar/Note.i"
	@echo "... bar/Note.s"
	@echo "... bar/Size.o"
	@echo "... bar/Size.i"
	@echo "... bar/Size.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

